import os
import re
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Tuple
import hashlib

class FileRenamer:
    def __init__(self):
        self.operations = []
        self.preview_data = []
        self.file_cache = {}
        self.text_watermark = "⚡ Generated by PremiumFileRenamer Pro (c) 2025 Dabeey"
        self.ascii_watermark = r"""
        ██████╗ ███████╗██████╗ ██████╗ 
        ██╔══██╗██╔════╝██╔══██╗██╔══██╗
        ██████╔╝█████╗  ██████╔╝██████╔╝
        ██╔═══╝ ██╔══╝  ██╔══██╗██╔═══╝ 
        ██║     ██      ██║  ██║██║     
        ╚═╝     ╚═╝     ╚═╝  ╚═╝╚═╝     
                    by Dabeey™
        """

    def _show_watermark(self):
        """Displays the ASCII art and text watermark"""
        print(self.ascii_watermark)
        print(f"\n{self.text_watermark}\n{'='*50}")

    def generate_preview(self, files: List[str], rules: Dict) -> List[Tuple[str, str]]:
        self._show_watermark()
        print(f"{self.text_watermark} | Generating preview...")
        
        self.preview_data.clear()
        
        for i, filepath in enumerate(files, start=rules.get('num_start', 1)):
            original = Path(filepath)
            new_name = self._apply_rules(original, rules, i)
            self.preview_data.append((filepath, str(new_name)))
            print(f"{self.text_watermark} | Preview: {original.name} → {new_name.name}")
        
        print(f"{self.text_watermark} | Preview complete for {len(files)} files")
        return self.preview_data

    def execute_rename(self) -> Dict:
        self._show_watermark()
        print(f"{self.text_watermark} | Starting rename operation...")
        
        results = {'success': 0, 'failed': 0}
        
        for original, new in self.preview_data:
            try:
                os.rename(original, new)
                self.operations.append((new, original))
                results['success'] += 1
                print(f"{self.text_watermark} | Renamed: {Path(original).name} → {Path(new).name}")
            except Exception as e:
                results['failed'] += 1
                print(f"{self.text_watermark} | Error renaming {Path(original).name}: {str(e)}")
        
        print(f"{self.text_watermark} | Operation complete: {results['success']} successful, {results['failed']} failed")
        return results

    def undo_last_operation(self) -> Dict:
        self._show_watermark()
        print(f"{self.text_watermark} | Starting undo operation...")
        
        results = {'undone': 0, 'failed': 0}
        
        while self.operations:
            new, original = self.operations.pop()
            try:
                os.rename(new, original)
                results['undone'] += 1
                print(f"{self.text_watermark} | Undone: {Path(new).name} → {Path(original).name}")
            except Exception as e:
                results['failed'] += 1
                print(f"{self.text_watermark} | Error undoing {Path(new).name}: {str(e)}")
        
        print(f"{self.text_watermark} | Undo complete: {results['undone']} undone, {results['failed']} failed")
        return results

    def _apply_rules(self, original: Path, rules: Dict, sequence: int) -> Path:
        """Apply all renaming rules to a file path"""
        if rules['mode'] == 0:  # Prefix/Suffix
            stem = f"{rules.get('prefix', '')}{original.stem}{rules.get('suffix', '')}"
        elif rules['mode'] == 1:  # Complete Replacement
            stem = rules['new_name']
        else:  # Pattern
            stem = self._apply_pattern(original.stem, rules['pattern'], sequence)
        
        stem = self._apply_case(stem, rules.get('case', 'keep'))
        
        if rules.get('num_digits', 0) > 0:
            seq_str = f"{sequence:0{rules['num_digits']}d}"
            stem = f"{stem}_{seq_str}" if stem else seq_str
        
        if rules.get('hash'):
            file_hash = self._get_file_hash(original, rules['hash'])
            stem = f"{file_hash}_{stem}" if stem else file_hash
        
        ext = self._get_new_extension(original, rules)
        return original.parent / f"{stem}{ext}"

    def _apply_pattern(self, original: str, pattern: str, sequence: int) -> str:
        replacements = {
            '{name}': original,
            '{num}': str(sequence),
            '{date}': datetime.now().strftime('%Y%m%d'),
            '{time}': datetime.now().strftime('%H%M%S')
        }
        result = pattern
        for key, value in replacements.items():
            result = result.replace(key, value)
        return result

    def _apply_case(self, text: str, case: str) -> str:
        if case == 'lowercase':
            return text.lower()
        elif case == 'uppercase':
            return text.upper()
        elif case == 'title case':
            return text.title()
        return text
    

    def _get_file_hash(self, filepath: Path, length: int) -> str:
        if filepath not in self.file_cache:
            with open(filepath, 'rb') as f:
                self.file_cache[filepath] = hashlib.md5(f.read()).hexdigest()
        return self.file_cache[filepath][:length]

    def _get_new_extension(self, original: Path, rules: Dict) -> str:
        ext_mode = rules.get('ext_mode', 0)
        if ext_mode == 0:
            return original.suffix
        elif ext_mode == 1:
            new_ext = rules.get('new_ext', '').strip()
            return f".{new_ext}" if new_ext else ''
        return ''